# Generated by Django 3.1.3 on 2020-11-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='condidats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('date_naiss', models.DateField(blank=True, null=True)),
                ('tel', models.IntegerField(default='')),
                ('disponibilite', models.IntegerField(default=0)),
                ('nbr_ann_exp', models.IntegerField(default=0)),
                ('cv', models.FileField(default='', upload_to='')),
                ('message', models.TextField(default='')),
                ('statut_mail', models.CharField(default='valide', max_length=30)),
                ('etat', models.CharField(default='nouvelle', max_length=30)),
            ],
        ),
    ]
